### PR TITLE
Add analysis of transformed jsx functions as islands

### LINKED ISSUE #1: `isFunctionIsland` test when already JSX transformed (and a couple of other tiny issues)
Hello,

First of all, thanks for this! It's great to see smaller tools separate from monolithic frameworks.

I'm trying to use this in rollup/vite's transform step, which has already gone through the jsx-runtime transform. Do you think it's worth adding a condition in `isFunctionIsland` to handle `_jsxs` and `_jsx` function calls in the return statement? That way, it doesn't need to take over the full parsing from source.

Example pre-transformed source example:

```js
_jsxs(Breadcrumbs, {
  children: [
    _jsx(BreadcrumbLink, {
      href: "/link-01",
      children: "One"
    }), _jsx(BreadcrumbLink, {
      href: "/link-02",
      children: "Two"
    }), _jsx(BreadcrumbLink, {
      href: "/link-03",
      children: "Three"
  })]
})
```

Also, just a few tiny issues I've noticed: 

- Looks like it just bundles index.js, so ./ast isn't in the output — I get a `Missing "./ast" specifier in "@dumbjs/preland" package` error when trying to `import { astFromCode } from '@dumbjs/preland/ast'`

- readFile is not imported from node:fs, so it fails in `readSourceFile` here:
https://github.com/dumbjs/preland/blob/main/src/index.js#L9C18-L9C26

### PR DESCRIPTION
**Pull request by barelyhuman**
Fixes: #1

### CODE REVIEW

**Comment by barelyhuman** [comment]
@coxmi, if you are using `npm` or `pnpm` could you try the following out 

```sh
npm i https://github.com/dumbjs/preland.git#1-transformed-jsx-check
```

and see if suffices the requirement? 

I've added ways to handle other transpile identifiers but I'm not sure of the name of the option yet ( `transpiledIdentifiers` ), so if the API seems okay, I would start adding more test cases for the same

**Comment by coxmi** [comment]
@barelyhuman sorry for the late reply, but yep this seems good to me! One thing I did notice separately is that there's also a `_jsxDEV` function, so it might be worth adding that too 🙂

**Comment by barelyhuman** [comment]
You can add that in the `isFunctionIsland`'s options if you are running the transpilation in dev mode. i'll add a way to extend the findIslands with same today

**Comment by barelyhuman** [comment]
You should be able to pass a modied `isFunctionIsland` in the options of `findIslands` now. :) 
The default set is already exported as `DEFAULT_TRANSPILED_IDENTIFIERS` 

Hopefully that handles the scenario where you need this 

The released beta is `0.0.0-beta.6` , same install command 

```sh
npm i @dumbjs/preland@beta
```

**Pull request merged**
